--------------------
-- CREATE WAREHOUSES
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS CCLAVE_DEV_WH WAREHOUSE_SIZE=XSMALL INITIALLY_SUSPENDED=TRUE AUTO_SUSPEND=60;
CREATE WAREHOUSE IF NOT EXISTS CCLAVE_PRD_WH WAREHOUSE_SIZE=XSMALL INITIALLY_SUSPENDED=TRUE AUTO_SUSPEND=60;

CREATE WAREHOUSE IF NOT EXISTS CCLAVE_ORCHESTRATION_DEV_WH WAREHOUSE_SIZE=XSMALL INITIALLY_SUSPENDED=TRUE AUTO_SUSPEND=60;
CREATE WAREHOUSE IF NOT EXISTS CCLAVE_ORCHESTRATION_PRD_WH WAREHOUSE_SIZE=XSMALL INITIALLY_SUSPENDED=TRUE AUTO_SUSPEND=60;
