--------------------
---- CREATE OBJECTS
USE ROLE SYSADMIN;
-- DATABASES
CREATE DATABASE IF NOT EXISTS CCLAVE_DEV;
CREATE DATABASE IF NOT EXISTS CCLAVE_PRD;

-- SCHEMAS
CREATE SCHEMA IF NOT EXISTS CCLAVE_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS CCLAVE_DEV._ORCHESTRATION;
CREATE SCHEMA IF NOT EXISTS CCLAVE_PRD.RAW;
CREATE SCHEMA IF NOT EXISTS CCLAVE_PRD._ORCHESTRATION;
