--------------------
---- CREATE ROLES:
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS CCLAVE_DEV_SERVICE_ACCOUNT_ROLE;
CREATE ROLE IF NOT EXISTS CCLAVE_PRD_SERVICE_ACCOUNT_ROLE;

USE ROLE SYSADMIN;
GRANT ROLE CCLAVE_DEV_SERVICE_ACCOUNT_ROLE TO ROLE SYSADMIN;
GRANT ROLE CCLAVE_PRD_SERVICE_ACCOUNT_ROLE TO ROLE SYSADMIN;

--------------------
---- GRANT PRIVILEGES:
USE ROLE SECURITYADMIN;

-- FOR CCLAVE_DEV_SERVICE_ACCOUNT_ROLE
GRANT USAGE ON WAREHOUSE CCLAVE_DEV_WH TO ROLE CCLAVE_DEV_SERVICE_ACCOUNT_ROLE;
-- RAW DATA ACCESS
GRANT USAGE ON DATABASE CCLAVE_DEV TO ROLE CCLAVE_DEV_SERVICE_ACCOUNT_ROLE;
GRANT USAGE ON SCHEMA CCLAVE_DEV.RAW TO ROLE CCLAVE_DEV_SERVICE_ACCOUNT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CCLAVE_DEV.RAW TO ROLE CCLAVE_DEV_SERVICE_ACCOUNT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CCLAVE_DEV.RAW TO ROLE CCLAVE_DEV_SERVICE_ACCOUNT_ROLE;
-- FUTURE DATA ACCESS
GRANT CREATE SCHEMA ON DATABASE CCLAVE_DEV TO ROLE CCLAVE_DEV_SERVICE_ACCOUNT_ROLE;

-- FOR CCLAVE_PRD_SERVICE_ACCOUNT_ROLE
GRANT USAGE ON WAREHOUSE CCLAVE_PRD_WH TO ROLE CCLAVE_PRD_SERVICE_ACCOUNT_ROLE;
-- RAW DATA ACCESS
GRANT USAGE ON DATABASE CCLAVE_PRD TO ROLE CCLAVE_PRD_SERVICE_ACCOUNT_ROLE;
GRANT USAGE ON SCHEMA CCLAVE_PRD.RAW TO ROLE CCLAVE_PRD_SERVICE_ACCOUNT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CCLAVE_PRD.RAW TO ROLE CCLAVE_PRD_SERVICE_ACCOUNT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CCLAVE_PRD.RAW TO ROLE CCLAVE_PRD_SERVICE_ACCOUNT_ROLE;
-- FUTURE DATA ACCESS
GRANT CREATE SCHEMA ON DATABASE CCLAVE_PRD TO ROLE CCLAVE_PRD_SERVICE_ACCOUNT_ROLE;
