--------------------
---- CREATE USERS:
USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS CCLAVE_DEV_SERVICE_ACCOUNT_USER
    PASSWORD = 'your_dev_password'
    COMMENT= 'Service account for dbt in the development (DEV) environment of the CCLAVE project.'
    DEFAULT_WAREHOUSE = CCLAVE_DEV_WH
    DEFAULT_ROLE= CCLAVE_DEV_SERVICE_ACCOUNT_ROLE
    MUST_CHANGE_PASSWORD=FALSE;
    
CREATE USER IF NOT EXISTS CCLAVE_PRD_SERVICE_ACCOUNT_USER
    PASSWORD = 'your_prd_password'
    COMMENT= 'Service account for dbt in the production (PRD) environment of the CCLAVE project.'
    DEFAULT_WAREHOUSE = CCLAVE_PRD_WH
    DEFAULT_ROLE= CCLAVE_PRD_SERVICE_ACCOUNT_ROLE
    MUST_CHANGE_PASSWORD=FALSE;

--------------------
---- GRANT ROLES TO USERS
USE ROLE USERADMIN;
GRANT ROLE CCLAVE_DEV_SERVICE_ACCOUNT_ROLE TO USER CCLAVE_DEV_SERVICE_ACCOUNT_USER;
GRANT ROLE CCLAVE_PRD_SERVICE_ACCOUNT_ROLE TO USER CCLAVE_PRD_SERVICE_ACCOUNT_USER;
